// Push fresh "Why this could be the place" copy for every city.
// Tone: confident, specific, full-throated — grounded in real geography + an
// honest tradeoff so it doesn't read like marketing. Anchors: what the city is
// objectively best at (the strongest measured axes), the lived-in detail you'd
// notice on a walk, and the tradeoff you'd notice on day three.
import pg from "pg";
import { execSync } from "node:child_process";

const W = {
  // ── Pacific Coast / PNW ─────────────────────────────────────────────────
  "Santa Barbara, CA": "Santa Barbara does the hard California thing: stays warm and beautiful without going dead. The Santa Ynez wall and the Pacific frame an actual lived-in downtown — State Street stacks 70+ social spots inside a walkable core, the climate is functionally year-round, and you can walk from coffee to the beach. Tradeoff is the price tag and the polish, but mountain backdrop + ocean horizon + real café density is genuinely rare.",
  "San Luis Obispo, CA": "SLO is the Central Coast's most livable secret — a college town in a vineyard valley with a creek through downtown and a Spanish-mission grid that just plain works on foot. Thursday farmers' market is a local ritual, not a tourist set piece; weather almost never punishes you. Smaller than SB and not coastal, but more honest about itself, and the mountains start at the edge.",
  "Santa Cruz, CA": "Santa Cruz is the closest you get to Bled energy on the US coast — ocean on one side, redwoods on the other, a downtown that's lived-in rather than performed. The mountains rise straight up from town, the surf shapes daily rhythm, and the UC presence keeps cafés and bookshops in business year-round. Tradeoff is the housing math and a counter-culture edge that's either charming or grating.",
  "Carmel-by-the-Sea, CA": "Carmel is pure beauty distilled — an absurdly walkable village, architecture curated tight, Carmel Beach delivering world-class scenery at the end of any ordinary stroll. Streets are intimate and lush; everything is on foot. The real test is whether sheer beauty earns past the wealth signal, or whether resort polish becomes its own discomfort.",
  "Monterey / Pacific Grove, CA": "Pacific Grove is Monterey's better-kept secret — a quiet Victorian grid on the bay with cypress headlands and a Mediterranean climate that's mild every month. The walkable core is small but real (bookshops, breakfast spots, the rec trail running right to the water), and Monterey Bay sunsets are the daily payoff. You give up restaurant density for setting.",
  "Ventura, CA": "Ventura is the less-grand, more usable Santa Barbara — same coast, same climate, half the polish, a real working downtown. Main Street has actual residents; the pier is a working pier; the mountains rise within reach. The case is the things you came for (ocean, walkability, year-round weather) are intact while the wealth signal is way lower.",
  "Hood River, OR": "Hood River is the Columbia Gorge made walkable — a tight downtown perched between river and mountain, with the Cascades to the south and sixty-mile water views. Coffee, beer, and orchard country are all on foot. Tradeoff is the size (~8k), gray winters, and the wind that makes it the windsurfing capital is sometimes a wind tax.",
  "Ashland, OR": "Ashland is theater in a Cascade foothills valley — Shakespeare Festival as the cultural spine, Lithia Park spilling along the creek behind it, a Plaza-anchored downtown with bookstores and cafés that stay full year-round. Small mountain town that punches culturally well above its weight; tradeoff is late-summer wildfire smoke and the price of living somewhere that's been discovered.",
  "Bellingham, WA": "Bellingham is where the Salish Sea meets Mount Baker — Fairhaven's brick Victorian core, the bay at your feet, the North Cascades half an hour east. Real college-town pulse without college-town disposability. Tradeoff is the gray winter — you're committing to PNW light — but locals say it's the deal they take to live where they live.",
  "Bend, OR": "Bend is high-desert with the Cascades inside the city limits — three hundred days of sun, the Deschutes River through downtown, peaks visible from every street. Twenty-plus breweries support a real Old Mill / Downtown walkable core. Honest tradeoffs are altitude, summer smoke, and growth (it's been discovered) — but the climate-plus-landscape ratio is hard to beat.",

  // ── Southeast Coast ─────────────────────────────────────────────────────
  "Charleston, SC": "Charleston is the East Coast's most lived-in historic town — 18th-century streetscapes that aren't a museum, a peninsula bound by water on three sides, food culture that competes with anywhere. Cannonborough / Elliotborough is where locals actually live. Tradeoff is summer (humid, hot, hurricane-aware), so you'd pick October–May to test it.",
  "Savannah, GA": "Savannah is one of the few American cities that designed in livability from day one — the 1733 oak-shaded squares are still the daily rhythm of walking. North of Forsyth has real shops, real residents, real cafés. Tradeoff is a summer that's a different climate and tourist gravity around River Street that's real, but you live north of it.",
  "St. Augustine, FL": "St. Augustine packs Spanish-colonial walkability into a flat coastal grid most US cities can't approach — brick streets, balcony shadows, the Bridge of Lions framing the bay. Off-season it's quiet and very real. Florida summer is Florida summer and St. George Street is touristy and loud, but both are manageable if you pick your blocks and your months.",
  "Beaufort, SC": "Beaufort is the Lowcountry's calm twin — antebellum streets along the river, marsh and live-oak everywhere, slower than Charleston without giving up the looks. The downtown is small but coherent (waterfront park, bookshop, cafés). Honest version: it's quiet, you'd notice it especially in summer.",
  "Cape May, NJ": "Cape May is a postcard-real Victorian beach town at the southern tip of the Jersey shore — the entire central district is a National Historic Landmark of gingerbread, with the beach two blocks away and Washington Street Mall as the pedestrian spine. Off-season it goes nearly silent — that's either rest or a death-test.",
  "St. Petersburg, FL": "St. Pete is the Gulf-side surprise — a walkable downtown waterfront with serious museums (Dalí, Chihuly), 360+ sunny days, and the Skyway sweeping across Tampa Bay. The Edge District / Grand Central is where it actually lives. Summer is a sauna; the other eight months are what people are buying.",
  "Newburyport, MA": "Newburyport is what New England would design if it could — a Federal-era brick downtown perched at the mouth of the Merrimack, with a working waterfront, a substantial bookstore, and Plum Island's wildlife refuge fifteen minutes away. Small, polished but lived-in. Winter is real winter — that's the test.",
  "Annapolis, MD": "Annapolis is colonial walkability done right — brick streets running down to the Bay, the Naval Academy giving it a permanent rhythm, City Dock and Eastport across the bridge. Real maritime daily life, not a theme. The state-capital + tourist + Navy mix is busy; that's also why the cafés stay open in February.",

  // ── Inland Appalachian / Mountains ──────────────────────────────────────
  "Asheville, NC": "Asheville is the Blue Ridge anchor — a creative, food-obsessed downtown wrapped in mountain rivers and the Biltmore estate, with Pisgah Forest at your back. Walkability is real but the city sprawls; pick downtown or West Asheville. Tourist load is heavy in fall and rents have moved hard — Asheville's been discovered. The setting and the food more than answer for both.",
  "Durango, CO": "Durango is the Animas River cutting through a Main Street that hasn't been ruined — narrow-gauge trains, San Juan peaks above, real high-desert sun and bluebird winter days. The downtown core is walkable, trails start at the edge of town, and the climate is paradoxically mild for the altitude. Tradeoff is true smallness and the long drive to anywhere bigger.",
  "Boulder, CO": "Boulder is where serious mountains meet a serious downtown — the Flatirons looming over the Pearl Street Mall, 300+ days of sun, a living grid of cafés and bookstores anchored by the university. Tradeoff is wealth and rent (Boulder priced itself), but Front Range access from your front door is genuinely rare.",
  "Santa Fe, NM": "Santa Fe is high-desert dignity — the Plaza, adobe walls, art and Indigenous craft as the spine, mountain light that no other US city offers. The downtown is small but dense; Atalaya trail starts at the edge. Tradeoffs are wealth, dry climate, and elevation; what you're buying is a place that looks like nowhere else in America.",
  "Charlottesville, VA": "Charlottesville is the southern college town done with taste — the Downtown Mall as a true pedestrian spine, UVA's Lawn as a daily walk, the Blue Ridge as backdrop, and a food-and-wine culture that punches well above the city's size. Tradeoffs are summer humidity and the politics-of-the-moment edge, but the daily experience is unusually good.",
  "Lexington, VA": "Lexington is the surprise — tiny (~7k), with a beautifully intact Victorian / Greek-revival downtown wrapped in horse country and the Blue Ridge, anchored by W&L and VMI. Slow-paced, scenic, easy to walk, much more interesting than its size suggests. Honest version: very small, very quiet.",
  "Staunton, VA": "Staunton is the Shenandoah Valley's most walkable little city — five National Register historic districts, Shakespeare in the Blackfriars Playhouse, a downtown that's been doing it right for a long time. The Blue Ridge frames it. Smaller and quieter than its press suggests; that's its appeal.",
  "Roanoke, VA": "Roanoke sits in a Blue Ridge bowl with the Mill Mountain star above the city and the Greenway running along the river. The downtown Market District has been seriously revived. Tradeoff is true regional smallness, but the mountain-walkability ratio is unusual for a city of this size and the climate is genuinely mild.",
  "Harrisonburg, VA": "Harrisonburg is the Shenandoah's quietly creative college town — JMU's energy without spring-break culture, a walkable downtown that's seen genuine reinvestment, the valley and the Massanutten visible from every direction. Affordable, scenic, easy. Tradeoff is the size — it's not pretending to be a big city.",
  "Morgantown, WV": "Morgantown is West Virginia's lone real city — WVU's pulse, the Monongahela cutting through, hills on every side, a downtown that's better than its press suggests. The rail-trail is the spine. Tradeoff is post-industrial bones and football-town intensity in fall — that's also why the place is alive year-round.",
  "Lewisburg, WV": "Lewisburg punches hilariously above its weight — a beautifully preserved Greenbrier Valley downtown with a real bookstore, real theater (Greenbrier Valley Theatre), and Carnegie Hall on a brick main street. Tradeoffs are size and isolation; what you get is a small mountain town that knows exactly what it is.",
  "Eureka Springs, AR": "Eureka Springs is the Ozark anomaly — a Victorian boomtown built on a hill so steep there are no parallel streets, every block staired into the next. Limestone springs, art-and-music scene, weird in a good way. Tradeoffs are the topography itself (everything is up or down) and the tourist economy that keeps it running.",

  // ── Ohio ────────────────────────────────────────────────────────────────
  "Cleveland (Tremont), OH": "Tremont sits on a bluff over the Cuyahoga valley with the downtown Cleveland skyline as your view — Victorian working-class houses gentrified just enough to anchor a real restaurant row, with Greek and Polish heritage still in evidence. Walkable from the Lincoln Park core. Honest tradeoff is lake-effect winter and the bigger-picture Cleveland question.",
  "Cleveland (Ohio City), OH": "Ohio City is the West Side Market neighborhood — Cleveland's most lived-in walkable district, with serious breweries (Great Lakes), the market hall as a daily anchor, quick light-rail downtown. Income mix is real, which is part of the texture. Tradeoff is the winter; Cleveland is Cleveland.",
  "Columbus (German Village), OH": "German Village is one of the densest brick-rowhouse neighborhoods in the country — Schiller Park, the Book Loft (32 rooms), human-scale streets every block. Walking it feels older and tighter than most of the US. Tradeoff: small for a true city neighborhood; you cross into Schumacher Place or downtown for variety.",
  "Columbus (Short North), OH": "The Short North is Columbus's actual urban core — gallery hop districts, OSU half a mile north, food and coffee in walking density, the lit arches overhead. Genuine year-round street life. Tradeoff is it's a strip more than a district; you live near High Street, not on it, to keep the noise honest.",
  "Cincinnati (Over-the-Rhine), OH": "Over-the-Rhine is the largest intact 19th-century historic district in the US — Italianate row houses by the hundred, Findlay Market as the heart, the streetcar connecting it to downtown. The transformation since 2010 is real and complicated. Walkable, beautiful, with active gentrification politics — you read that as you go.",

  // ── Pittsburgh ──────────────────────────────────────────────────────────
  "Pittsburgh (Squirrel Hill), PA": "Squirrel Hill is Pittsburgh's most consistently lived-in walkable neighborhood — Murray and Forbes intersecting at a real commercial spine, a stable Jewish core, Frick Park at the edge, denser resident base than Shadyside. Tradeoff is the Pittsburgh tax (gray winters, hilly bus routes) — but Squirrel Hill is what the city offers you that other US cities don't.",
  "Pittsburgh (South Side), PA": "South Side Flats give you river-and-slope geography most US cities can't deliver — East Carson Street stretching twelve blocks of bars, restaurants, and old-Pittsburgh architecture, Mt. Washington above, Monongahela below. Bar-heavy in the daytime test; that's also the character. Honest with itself.",
  "Pittsburgh (Strip District), PA": "The Strip is the city's market district — Penn Avenue as a sensory daily ritual (produce, fish, Polish, Italian, espresso), now with real housing in the brick warehouses. Walking it is what walking through a working downtown should feel like. Tradeoff is that residential is still emerging; you're early.",

  // ── PA small ────────────────────────────────────────────────────────────
  "Lancaster, PA": "Lancaster was platted in 1730 and it shows — a tight grid downtown, Central Market still doing what it's done for 290 years, brick and limestone everywhere. Amish country at the edges, real arts scene downtown, an unusually large concentration of independent shops. Flat and very walkable. Honest: surrounding sprawl is sprawl.",
  "Bethlehem, PA": "Bethlehem's Historic District is the Moravian core that founded the town in 1741 — limestone buildings, Main Street, and the SteelStacks reuse of Bethlehem Steel turning the south side into a serious music venue. Lehigh + Moravian colleges keep it alive. Tradeoff is winter and a city still finding its post-steel identity.",
  "Easton, PA": "Easton is the Lehigh-Valley dark horse — a colonial Centre Square, the Delaware confluence, a serious public market, and Lafayette College on the hill. Cheaper than Bethlehem, more interesting than its reputation. Winter is real winter; that's the only real cost.",
  "Jim Thorpe, PA": "Jim Thorpe is the 'Switzerland of America' for good reason — a Victorian downtown wedged in a deep Lehigh Gorge, the Asa Packer Mansion looking down, train depots and bell towers all intact. Tiny (~5k), tourist-heavy in fall, but the setting is genuinely uncommon for the East Coast and you can walk it end to end.",
  "Bellefonte, PA": "Bellefonte is the Centre County secret — a Victorian downtown along Spring Creek with the courthouse on the hill, ten minutes from Penn State but a different planet from State College. Walkable, scenic, very small. Honest version: small.",
  "Lewisburg, PA": "Lewisburg is the river-town college core — Bucknell on the hill, a beautifully intact downtown along Market Street, the Susquehanna at the edge. Real bookstore, real theater. Tradeoff is the size and the post-industrial countryside around it.",

  // ── New York upstate / Hudson Valley ────────────────────────────────────
  "Buffalo (Elmwood), NY": "Elmwood Village is Buffalo's most walkable strip — the village runs along Elmwood Avenue with Olmsted parks on both ends (Delaware Park, the Albright-Knox). Architecture is taut, food and coffee are serious, the lake is fifteen minutes out. Tradeoff: lake-effect winter is a real commitment.",
  "Buffalo (Allentown), NY": "Allentown is the historic-district companion to Elmwood — gas-lit streets, brownstones, the small theater scene, classic dive bars and serious restaurants in the same block. Smaller and rawer than Elmwood. The Buffalo winter is the Buffalo winter; locals shrug.",
  "Rochester (Park Ave), NY": "Park Avenue is Rochester's most consistent walkable district — a residential spine of brick houses, indie shops, a summer festival that takes over the street, Highland Park's lilacs nearby. Tradeoff is the rust-belt context and a winter that's not as bad as Buffalo but is still upstate.",
  "Ithaca, NY": "Ithaca is gorges, Cornell, a real Commons pedestrian downtown, and Cayuga Lake — a college town that doesn't disappear when school's out because the natural-foods / wine-trail / waterfall economy is genuine. Tradeoff is winter (long), and a small city is a small city.",
  "Saratoga Springs, NY": "Saratoga is famously the racing town but its actual life is the year-round Broadway corridor — walkable, restaurant-dense, mineral springs, a Skidmore-college pulse, the Adirondacks visible. August race-season chaos is the famous part; the other eleven months are why you'd actually live there.",
  "Hudson, NY": "Hudson is the Hudson Valley's most concentrated experiment — Warren Street as the spine of antiques, restaurants, design, and a downtown-Manhattan-in-exile sensibility that's spilled north. The river at the bottom, the Catskills as backdrop. Tradeoff is the gentrification arc is real.",
  "Beacon, NY": "Beacon is the Hudson Valley's small-but-serious city — Main Street one mile long, Dia:Beacon as the cultural anchor, the river and Mount Beacon framing daily life, Metro-North 90 minutes to NYC. Tradeoff is the prices have moved; the village is genuinely beautiful in return.",
  "Kingston, NY": "Kingston is the Hudson Valley's grown-up city — Stockade District as 17th-century stone heart, Rondout waterfront on the river, Catskills in view. Less polished than Hudson, more functional. Tradeoff is post-industrial bones still showing, which is also some of the charm.",

  // ── New England stretch ─────────────────────────────────────────────────
  "Burlington, VT": "Burlington is Lake Champlain with the Adirondacks across the water — Church Street's pedestrian mall as a real four-season social spine, UVM keeping the city year-round alive. Sailing, cycling, food, beer, and snow all within reach. The honest tradeoff is six months of cold; people don't apologize for it.",
  "Portland, ME": "Portland is the working harbor done right — Old Port's cobblestones with a fishing fleet still at the dock, Munjoy Hill above, ferries to the islands, a food scene that's defined the genre. Year-round walkable downtown. Winter is real; rents have moved up. Both are the price of a city that lives this well.",

  // ── Tennessee ───────────────────────────────────────────────────────────
  "Knoxville, TN": "Knoxville is the Tennessee River + Market Square + Old City — a downtown that revived faster than anyone predicted, the Smokies an hour east, UT keeping cafés open year-round. Climate is genuinely milder than the upper-South stereotypes. Tradeoff is summer heat and the regional sprawl beyond the core.",
  "Chattanooga, TN": "Chattanooga is the Tennessee River gorge city — Walnut Street Bridge crossing the river to North Shore, Lookout Mountain looming, downtown revived around the riverfront and Hunter Museum. Tradeoff is the Tennessee-summer heat and the city's still figuring out density past the core.",

  // ── Other ───────────────────────────────────────────────────────────────
  "Richmond, VA": "Richmond's Fan / Museum District / Carytown spine is one of the South's most consistently walkable urban runs — late-Victorian rowhouses, James River park trails through the middle of the city, food culture that takes itself seriously. Tradeoff is summer humidity and a southern-city racial/political weight the city is honest about.",
  "Frederick, MD": "Frederick is the MD-DC orbit's most authentic small downtown — Carroll Creek's linear park, brick everywhere, real shops and restaurants on Patrick and Market Streets, the Catoctin Mountains as backdrop. Twin commuter routes to DC and Baltimore make it functionally a third option. Tradeoff is the orbit pulls part of its identity.",
  "Greenville, SC": "Greenville is the Reedy River + Falls Park + a Main Street that's been national-press-level walkable for a decade. The Blue Ridge is forty-five minutes north. Tradeoff is the Southern-city growth tax (rents, traffic) — but Main Street here is what other Southern cities are still trying to build.",

  // ── Calibration / reference (Slovenia + Pittsburgh controls) ────────────
  // Honest framing: these aren't candidates to visit; they anchor what the
  // metrics + the gut scale actually mean.
  "Bled, Slovenia": "Bled is the calibration anchor — alpine lake, church on the island, castle on the cliff, all visible from every angle. This is what 'setting' at 10 actually looks and feels like. The metric isn't asking you to find Bled in the US; it's asking how close any candidate even gets.",
  "Piran, Slovenia": "Piran is the other anchor — Venetian Adriatic town, Tartini Square opening to the sea, walls climbing to St. George's tower, lived in by people who actually live there. The point isn't to recreate this anywhere; it's to be honest about what 'lived' means.",
  "Ljubljana, Slovenia": "Ljubljana is the lived-in-city version of the calibration — Prešeren Square, the Ljubljanica with its bridges, Plečnik's architecture, a working European capital that's still small enough to walk. ~8 is the realistic ceiling for a real city, not a postcard.",
  "Pittsburgh (Shadyside), PA": "Shadyside is the owner's calibration — Walnut Street's retail strip is the most-walked Pittsburgh district, but it scored COLD on the felt test because retail is not life. Keeping it here catches any algorithm that mistakes 'shops on a street' for actual aliveness.",
  "Pittsburgh (Lawrenceville), PA": "Lawrenceville is the other COLD calibration — Butler Street's bar/restaurant strip looks like everything the metrics reward, but the felt rating came in low because consumption isn't community. Anchors the floor of the felt scale.",
  "Sewickley, PA": "Sewickley is a controlled benchmark — borough Main Street, Allegheny river edge, a polished suburban village. Unrated by the owner; left in to see what 'pleasant but bounded' looks like in the data.",
  "Oakmont, PA": "Oakmont is a controlled benchmark — Allegheny River Boulevard's small commercial strip in a quiet borough. Left in the dataset to expose whether the algorithm over-rewards a thin commercial spine.",
  "Verona, PA": "Verona is a controlled benchmark — small Allegheny River borough main street, similar profile to Oakmont. Held in the set to see whether two similar small boroughs read similarly.",
  "Allison Park, PA": "Allison Park is the floor — Hampton Township suburban geography, car-dependent by design. Should score low on every walkability and aliveness metric. If it doesn't, the metric is wrong.",
};

const pw = execSync("security find-generic-password -a livability-scout -s supabase-db-password -w", { encoding: "utf8" }).trim();
const c = new pg.Client({ host: "aws-1-us-west-2.pooler.supabase.com", port: 5432, user: "postgres.fitjkrmiwkdolxhitroc", password: pw, database: "postgres", ssl: { rejectUnauthorized: false } });
await c.connect();
const { rows } = await c.query("select id, name from cities order by name");
let updated = 0, missing = [];
for (const r of rows) {
  const text = W[r.name];
  if (!text) { missing.push(r.name); continue; }
  await c.query("update cities set why=$1 where id=$2", [text, r.id]);
  updated++;
}
console.log(`updated ${updated} of ${rows.length}`);
if (missing.length) console.log("MISSING (no copy written):", missing.join(", "));
await c.end();
